# Purpose
Matrix Inversion via numpy with a square matrix<br>
Computing weights for a linear equation y=Xw

In [ ]:
import numpy as np

**Creating a dummy matrix, X, and y vector**

In [2]:
X = np.array([[1, 25.,  2.,  9.],
               [1, 5., 26., -5.],
               [1, 3.,  7., -1.],
               [1, 24., 8., -2.]])
X,X.shape

# square matrix for our X features

(array([[ 1., 25.,  2.,  9.],
        [ 1.,  5., 26., -5.],
        [ 1.,  3.,  7., -1.],
        [ 1., 24.,  8., -2.]]),
 (4, 4))

In [3]:
y = np.array([13.,20.,15.,4.])
y,y.shape

# y vector for our target

(array([13., 20., 15.,  4.]), (4,))

**Is the X matrix invertable?**

Check 1 using the determinants

In [4]:
np.linalg.det(X) # =/= 0; means it is invertable
# yes because it is not equal to zero

-3889.999999999999

Check 2 using identity matrix. (ignore rounding errors)

In [7]:
np.dot((np.linalg.inv(X)),X)
# should produce an identity matrix if invertable
# yes it is invertable

array([[ 1.00000000e+00, -1.33226763e-15,  0.00000000e+00,
         0.00000000e+00],
       [-6.93889390e-18,  1.00000000e+00, -5.55111512e-17,
         0.00000000e+00],
       [ 0.00000000e+00,  1.11022302e-16,  1.00000000e+00,
         2.77555756e-17],
       [ 0.00000000e+00,  4.44089210e-16,  0.00000000e+00,
         1.00000000e+00]])

In [8]:
# both checks are not necessary.  two ways to check.

**Solve for the weights**

In [9]:
# w = dot(inv(X),y)

In [10]:
w = np.dot((np.linalg.inv(X)),y)
w

array([13.72390746, -0.49485861,  0.56143959,  1.16940874])

In [11]:
y

array([13., 20., 15.,  4.])

In [13]:
np.dot(X,w)

array([13., 20., 15.,  4.])

In [ ]:
# y = dot(X,w)