# Purpose 
Singular Value Decomposition (SVD) walkthrough with numpy

In [3]:
import numpy as np

**A = UDV.T**

In [8]:
A = np.array([[25,2,-5],
              [3,-2,1],
              [5,7,4.],
              [2,3,4]])

A, 'm x n', A.shape
# m x n shape

(array([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.],
        [ 2.,  3.,  4.]]),
 'm x n',
 (4, 3))

In [9]:
U, d, VT = np.linalg.svd(A)

In [10]:
U, 'm x m', U.shape
# m x m shape
# left singular vector: U

(array([[-0.9726183 ,  0.19750537,  0.07504387,  0.09681783],
        [-0.09719058,  0.08953374, -0.86048107, -0.49204677],
        [-0.19985198, -0.82963752,  0.20927216, -0.47745778],
        [-0.06802074, -0.51446761, -0.45841673,  0.72149176]]),
 'm x m',
 (4, 4))

In [11]:
d, 'n', d.shape
# n shape
# singular values: d

(array([26.22145632,  9.50138038,  3.02638387]), 'n', (3,))

In [12]:
VT, 'n x n', VT.shape
# n x n shape
# right singular vector V.T which is transposed automatically in the output

(array([[-0.98172772, -0.127906  ,  0.14089263],
        [ 0.00306404, -0.75093533, -0.66036864],
        [-0.19026637,  0.6478705 , -0.73760594]]),
 'n x n',
 (3, 3))

In [13]:
D = np.concatenate((np.diag(d), np.zeros((1,d.shape[0]))), axis=0)
D, 'm x n', D.shape
# m x n shape
# D is the diagonal of the singular values, d, with an extra row concatenated to allow
# for matrix multiplication that will be used to solve for A

(array([[26.22145632,  0.        ,  0.        ],
        [ 0.        ,  9.50138038,  0.        ],
        [ 0.        ,  0.        ,  3.02638387],
        [ 0.        ,  0.        ,  0.        ]]),
 'm x n',
 (4, 3))

In [20]:
# A = UDV.T
# m x m, m x n, n x n = m x n

np.dot(U, np.dot(D,VT)), 'm x n', np.dot(U, np.dot(D,VT)).shape

(array([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.],
        [ 2.,  3.,  4.]]),
 'm x n',
 (4, 3))

In [25]:
A, 'm x n', A.shape
# m x n shape

(array([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.],
        [ 2.,  3.,  4.]]),
 'm x n',
 (4, 3))